### ISSUE TITLE
iwconfig output

### ISSUE THREAD

**Issue by balkin** [denbeigh2000/goi3bar#14]
I'm not sure why, but on my system, iwconfig never shows the signal strength. So, I always get the following error: `Error generating output for network: Couldn't match strength`

```
wlp5s0    IEEE 802.11abg  ESSID:"lalala"  
          Mode:Managed  Frequency:2.462 GHz  Access Point: 30:B5:C2:08:5A:D9   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off
```

I think in this case goi3bar can just skip the signal strength.
That's on my laptop with `wl` driver for Broadcom wi-fi chip.

**Comment by denbeigh2000** [comment]
Cheers, this should be resolved by 4d835ba.
