### ISSUE TITLE
goi3bar fails to load with "Error: status_command not found or is missing a library dependency (exit 127)"

### ISSUE THREAD

**Issue by dharmit** [denbeigh2000/goi3bar#18]
`bar {` entry in my `~/.i3/config` looks like:

```
bar {
    status_command goi3bar -config-path ~/.i3/goi3status.json
}
```

And the config file was taken from the `README.md` on the repo:

```json
{
    "colors": {
        "color_crit": "#FF0000",
        "color_warn": "#FFA500",
        "color_ok": "#00FF00",
        "color_general": "#FFFFFF"
    },
    "interval": "5s",
    "entries": [
        {
            "package": "memory",
            "name": "memory",
            "options": {
                "interval": "10s",
                "warn_threshold": 75,
                "crit_threshold": 85
            }
        }
    ]
}
```

Running the `goi3bar` command as mentioned in i3config file works without any errors and I see output beng emitted onto stdout every few seconds. However, it doesn't run through i3wm and throws error as mentioned in the subject.

**Comment by denbeigh2000** [comment]
Looks like this works for me because I set my `$PATH` in my `~/.xinitrc` before my i3 process is instantiated. I'll make a note of this in the README.
